// EDITA AQUÍ TUS CÓDIGOS PERMITIDOS
// - code: lo que escribe el invitado (no distingue mayúsculas/minúsculas)
// - name: cómo quieres que aparezca en pantalla
const CODES = [
  { code: "0401", name: "Mauro y Francesca" },
  { code: "oliviero e manuela", name: "Oliviero e Manuela" },
  { code: "andrea e sara", name: "Andrea e Sara" },
  { code: "vanessa e Simone", name: "Vanessa e Simone" },
  { code: "marco e elena", name: "Marco e Elena" },
  { code: "2030", name: "Daniel e Elisa" },
  { code: "2919", name: "Mauro y Josefina" },
  { code: "2705", name: "Katherine" },
  { code: "enzo", name: "Enzo Lizama"},
  { code: "fabrizio", name: "Fabrizio Pirola" },
  { code: "chiara", name: "Chiara Albanese" },
  { code: "gianluca e valentina", name: "Gianluca e Valentina" },
  { code: "manuel e beatrice", name: "Manuel e Beatrice" },
  { code: "2107", name: "Aldo e Azurra" },
  { code: "miguel", name: "Miguel Chéron" },
  { code: "mayte", name: "Mayte Diaz Del Olmo" },
  { code: "2003", name: "Susana Nieto" },
  { code: "manuel y Sofia", name: "Manuel y Sofia" },
  { code: "rosario", name: "Rosario Flores" },
  { code: "mike", name: "Mike Gomez" },
  { code: "nito", name: "Nito Gomez" },
  { code: "alejandro", name: "Alejandro Ruiz" },
  { code: "Chris", name: "Crystal Cornejo" },
  { code: "Chris", name: "Sebastian Reyes" },
  { code: "rocio y nia", name: "Rocio y Nia" },
  { code: "magra y chris", name: "Magra y Chris" },
  { code: "rubén y victoria", name: "Rubén y Victoria" },
  { code: "abraham y rosa", name: "Abraham y Rosa" },
  { code: "diego y mirella", name: "Diego y Mirella" },
  { code: "0619", name: "Fiorella y Sergio" },
  { code: "0404", name: "Andrea e Elisa" },
  { code: "2108", name: "Giulia e Andrea" },
  { code: "2612", name: "Annalisa e Alessandro" },
  { code: "4521", name: "Kony Rivas" },
  { code: "4522", name: "Ana y Remco" },
  { code: "4520", name: "Nicole y Gerarld" },
];
