// EDITA AQUÍ TUS CÓDIGOS PERMITIDOS
// - code: lo que escribe el invitado (no distingue mayúsculas/minúsculas)
// - name: cómo quieres que aparezca en pantalla
const CODES = [
  { code: "0401", name: "Mauro e Francesca" },
  { code: "0909", name: "Oliviero e Manuela" },
  { code: "2306", name: "Andrea e Sara" },
  { code: "2005", name: "Vanessa e Simone" },
  { code: "2001", name: "Marco e Elena" },
  { code: "2030", name: "Daniel e Elisa" },
  { code: "2010", name: "Mauro y Josefina" },
  { code: "2705", name: "Katherine" },
  { code: "2712", name: "Enzo Lizama"},
  { code: "0712", name: "Fabrizio Pirola" },
  { code: "4523", name: "Chiara Albanese" },
  { code: "0709", name: "Gianluca e Valentina" },
  { code: "1914", name: "Beatrice e Manuel" },
  { code: "2107", name: "Aldo e Azurra" },
  { code: "2004", name: "Miguel Chéron" },
  { code: "1909", name: "Mayte Diaz Del Olmo" },
  { code: "2003", name: "Susana Nieto" },
  { code: "2729", name: "Manuel y Sofia" },
  { code: "1202", name: "Rosario Flores" },
  { code: "1026", name: "Mike y Carmen" },
  { code: "1025", name: "Nito Gomez" },
  { code: "1101", name: "Alejandro Ruiz" },
  { code: "1810", name: "Crystal Cornejo" },
  { code: "2504", name: "Sebastian Reyes" },
  { code: "0707", name: "Rocio y Nia" },
  { code: "1807", name: "Magra y Chris" },
  { code: "1501", name: "Rubén y Victoria" },
  { code: "1801", name: "Abraham y Rosa" },
  { code: "0710", name: "Diego y Mirella" },
  { code: "0619", name: "Fiorella y Sergio" },
  { code: "0404", name: "Andrea e Elisa" },
  { code: "2108", name: "Giulia e Andrea" },
  { code: "2612", name: "Annalisa e Alessandro" },
  { code: "2604", name: "Kony y Simone" },
  { code: "0905", name: "Ana y Remco" },
  { code: "4520", name: "Nicole y Gerarld" },
  { code: "0704", name: "Diego Simangas" },
  { code: "2601", name: "Maryloni y Fabio" },
  { code: "2709", name: "Andrea Murillo" },
  { code: "2509", name: "Karin Fernandini" },
  { code: "0510", name: "Ale Tejeda Tabini" },
  { code: "0225", name: "Samuele e Claudia" },
  { code: "1522", name: "Gianluca e Michela" },
  { code: "0209", name: "Anthony e Roberta" },
  { code: "2226", name: "Stefano e Annalisa" },
  { code: "2326", name: "Amerigo e Giulia" },
  { code: "2327", name: "Nicolò e Claudia" },
  { code: "2207", name: "Enrique Wong" },
  { code: "1508", name: "Carlos Henriquez" },
  { code: "2426", name: "Piera" },
  { code: "2402", name: "Monica y Luis" },
  { code: "1501", name: "Ivonne Medrano" },
  { code: "2201", name: "Carolina Condori" },
  { code: "2012", name: "Martin Hernández" },
  { code: "1002", name: "Michelle Ramos" },
  { code: "2203", name: "Daniela y Rodrigo" },
  { code: "2204", name: "Maria Luisa y Benito" },
  { code: "0001", name: "Tyna Ros" },
  { code: "0002", name: "Miguel" },
  { code: "0003", name: "Laura Prieto" },
  { code: "0004", name: "Fernando Molina" },
  { code: "0005", name: "María Berdejo" },
  { code: "0006", name: "Laura Guijarro" },
];
